version: "3"

services:
  staging:
    env_file:
      - .env
    container_name: staging
    image: 'staging-server'
    build:
      context: ./docker/nginx/staging
    ports:
      - ${STAGING_PORT}:80
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/staging/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/staging/logs/:/var/log/nginx
      - ./filesystem/staging:/var/www/html/staging:rw

  production:
    env_file:
      - .env
    container_name: production
    image: 'production-server'
    build:
      context: ./docker/nginx/production
    ports:
      - ${PRODUCTION_PORT}:80
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/production/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/production/logs/:/var/log/nginx
      - ./filesystem/production:/var/www/html/production:rw

  php:
    env_file:
      - .env
    container_name: php-srv
    image: php-srv
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:9000
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./filesystem/staging:/var/www/html/staging
      - ./filesystem/production:/var/www/html/production


  mysql:
    env_file:
      - .env
    container_name: mysql
    image: 'mysql'
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - "./docker/mysql/my.conf:/etc/mysql/conf.d/my.cnf"
      - "./docker/mysql/logs:/var/log/mysql"
      - ci-cd-workflow:/var/lib/mysql

  jenkins:
    env_file:
      - .env
    container_name: jenkins
    image: jenkins-srv
    build:
      context: ./docker/jenkins
    ports:
      - ${JENKINS_PORT}:8080
    volumes:
      - "./docker/jenkins/data:/var/jenkins_home"
    depends_on:
      - production
      - staging

  prometheus:
    env_file:
      - .env
    container_name: prometheus
    image: prometheus
    restart: unless-stopped
    build:
      context: ./docker/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - "./docker/prometheus/config:/etc/prometheus"
      - "./docker/prometheus/data:/prometheus"
    depends_on:
      - production
      - staging
      - mysql

  grafana:
    env_file:
      - .env
    container_name: grafana
    image: grafana
    restart: unless-stopped
    build:
      context: ./docker/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - "./docker/grafana/data:/var/lib/grafana"
      - "./docker/grafana:/etc/grafana"
    depends_on:
      - prometheus

  cadvisor:
    env_file:
      - .env
    container_name: cadvisor
    image: cadvisor
    restart: unless-stopped
    build:
      context: ./docker/cadvisor
    ports:
      - ${CADVISOR_PORT}:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - ./docker/cadvisor/logs:/var/log/cadvisor
    depends_on:
      - production
      - staging
      - php
      - mysql
      - jenkins
      - prometheus
      - grafana

volumes:
  ci-cd-workflow: