global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: mysql
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]